global using System.Linq;
global using System.Reflection;
global using Cinemachine;
global using FreeCameraControl.Properties;
global using HarmonyLib;
global using JetBrains.Annotations;
global using Kitchen;
global using KitchenMods;
global using PreferenceSystem;
global using UnityEngine;
global using UnityEngine.InputSystem;
global using UnityEngine.InputSystem.Users;
global using static FreeCameraControl.LoggingUtils;
global using Object = UnityEngine.Object;