global using JetBrains.Annotations;
global using Kitchen;
global using KitchenData;
global using KitchenMods;
global using ForceConsent.Properties;
global using PreferenceSystem;
global using System.Collections.Generic;
global using System.Reflection;
global using Unity.Collections;
global using Unity.Entities;
global using UnityEngine;
global using static ForceConsent.LoggingUtils;
global using System;
global using System.Linq;
global using ForceConsent;
global using Kitchen.Modules;